# Generated by Django 5.2.6 on 2026-04-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_is_hot_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grain&cereal', 'Grain & Cereal'), ('tuber', 'Tuber'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('livestock', 'Livestock'), ('seafood', 'Seafood'), ('dairy&egg', 'Dairy & Egg'), ('farmsupplies&inputs', 'Farm Supplies & Inputs'), ('organic&specialtyproducts', 'Organic & Specialty Products'), ('snacks&processedfoods', 'Snacks & Processed Foods'), ('farmservices&equipment', 'Farm Services & Equipment'), ('beverages', 'Beverages')], max_length=200),
        ),
    ]
