# Generated by Django 5.2.6 on 2026-04-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_profile_address_profile_bio_profile_farm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_out', 'Sent Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
